'use strict';

const { BaseProvider } = require('./base');
const logger = require('../utils/logger');

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Attempts to extract a title / objective from the prompt text.
 * Looks for common patterns like "title:", "objective:", or the first line.
 * @param {string} prompt
 * @returns {string}
 */
function extractTitle(prompt) {
  const titleMatch = prompt.match(/(?:title|name)\s*[:\-]\s*(.+)/i);
  if (titleMatch) return titleMatch[1].trim();

  const objectiveMatch = prompt.match(/(?:objective|goal|about)\s*[:\-]\s*(.+)/i);
  if (objectiveMatch) return objectiveMatch[1].trim();

  // Fall back to first non-empty line, capped at 80 chars
  const firstLine = prompt.split('\n').find(l => l.trim().length > 0) || '';
  return firstLine.slice(0, 80).trim() || 'Untitled';
}

// ---------------------------------------------------------------------------
// Lane generators
// ---------------------------------------------------------------------------

function generateArchitecture(prompt) {
  const title = extractTitle(prompt);
  return [
    '## Architecture Overview',
    '',
    '**Subject:** ' + title,
    '',
    'This document describes the high-level architecture derived from the provided context.',
    '',
    '---',
    '',
    '## Components',
    '',
    '- **Frontend Layer** — User-facing interface responsible for rendering and interaction.',
    '- **API Gateway** — Single entry point for all client requests; handles auth and routing.',
    '- **Business Logic Service** — Core domain rules and workflows.',
    '- **Data Store** — Persistent storage layer (relational + key-value cache).',
    '- **Background Workers** — Async jobs, scheduled tasks, and event consumers.',
    '',
    '---',
    '',
    '## Scope and Constraints',
    '',
    '- **In scope:** core user-facing features for the smallest useful increment (MVP slice).',
    '- **Out of scope:** multi-user, authentication, external integrations (non-goals).',
    '- **Constraint:** standalone delivery — no build step required.',
    '',
    '## Input / Output Contracts',
    '',
    '- **Input:** user actions (form submit, remove click), localStorage data.',
    '- **Output:** rendered idea list, persisted localStorage state.',
    '- **Interface:** DOM events + Web Storage API.',
    '',
    '## Data Flow',
    '',
    '1. User fills input → clicks Add → idea appended to list.',
    '2. First render reads from localStorage; each mutation writes back.',
    '3. Remove button deletes entry and triggers re-render.',
    '',
    '---',
    '',
    '## Risks',
    '',
    '| Risk | Likelihood | Mitigation |',
    '|------|------------|------------|',
    '| Single point of failure at Gateway | Medium | Deploy multiple replicas behind a load-balancer |',
    '| Data consistency across services | High | Use optimistic locking + event sourcing |',
    '| Over-complicated async flows | Low | Keep worker contracts simple; add circuit-breakers |',
    '',
    '---',
    '',
    '*Generated by MockProvider — replace with real LLM output before shipping.*',
  ].join('\n');
}

function generatePlanning(prompt) {
  const title = extractTitle(prompt);
  return [
    '## Tasks',
    '',
    '**Project:** ' + title,
    '',
    '| # | Task | Owner | Status |',
    '|---|------|-------|--------|',
    '| 1 | Define acceptance criteria | PM | TODO |',
    '| 2 | Technical spike / research | Engineering | TODO |',
    '| 3 | Implement core feature | Engineering | TODO |',
    '| 4 | Write unit + integration tests | QA | TODO |',
    '| 5 | Code review & merge | Engineering | TODO |',
    '| 6 | Deploy to staging | DevOps | TODO |',
    '| 7 | UAT sign-off | PM | TODO |',
    '| 8 | Production release | DevOps | TODO |',
    '',
    '---',
    '',
    '## Dependencies',
    '',
    '- Task 3 depends on Task 2 completing successfully.',
    '- Task 4 can start in parallel with the latter half of Task 3.',
    '- Task 6 requires Tasks 4 and 5 to be fully complete.',
    '',
    '---',
    '',
    '## Timeline',
    '',
    '| Phase | Duration | Notes |',
    '|-------|----------|-------|',
    '| Discovery | 1 day | Spike + research |',
    '| Implementation | 3 days | Core + tests |',
    '| Review & Deploy | 1 day | Code review, staging, UAT |',
    '',
    '*Total estimated: 5 working days.*',
    '',
    '---',
    '',
    '*Generated by MockProvider — replace with real LLM output before shipping.*',
  ].join('\n');
}

function generateResearch(prompt) {
  const title = extractTitle(prompt);
  return [
    '## Findings',
    '',
    '**Topic:** ' + title,
    '',
    '1. The subject area is well-established with multiple mature solutions available.',
    '2. Key decision factors include: performance, maintainability, community support, and licensing.',
    '3. Preliminary data suggests a hybrid approach may outperform pure alternatives.',
    '4. No critical blocking issues identified at this stage.',
    '',
    '---',
    '',
    '## Sources',
    '',
    '- Internal codebase analysis',
    '- Industry benchmark reports (2024–2025)',
    '- Official documentation of candidate libraries',
    '- Community discussions (GitHub Issues, Stack Overflow)',
    '',
    '---',
    '',
    '## Recommendations',
    '',
    '1. **Short-term:** Adopt the simplest viable solution to unblock development.',
    '2. **Mid-term:** Run a time-boxed A/B comparison between top two candidates.',
    '3. **Long-term:** Revisit the decision after first production metrics are available.',
    '',
    '---',
    '',
    '*Generated by MockProvider — replace with real LLM output before shipping.*',
  ].join('\n');
}

/**
 * Builds the HTML for the Idea Backlog app.
 * Content is assembled from string arrays to keep the source clean.
 * The escHtml helper inside the emitted script handles XSS for user-supplied titles.
 */
function generateBuild() {
  const style = [
    '    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }',
    '    body {',
    '      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;',
    '      background: #0f1117; color: #e2e8f0;',
    '      min-height: 100vh; display: flex; flex-direction: column;',
    '      align-items: center; padding: 2rem 1rem;',
    '    }',
    '    h1 { font-size: 1.75rem; font-weight: 700; margin-bottom: 1.5rem; color: #a78bfa; }',
    '    .card {',
    '      background: #1e2130; border: 1px solid #2d3148; border-radius: 12px;',
    '      padding: 1.5rem; width: 100%; max-width: 560px; margin-bottom: 1.5rem;',
    '    }',
    '    .form-row { display: flex; gap: 0.75rem; flex-wrap: wrap; }',
    '    input[type="text"] {',
    '      flex: 1 1 200px; padding: 0.6rem 0.9rem; border-radius: 8px;',
    '      border: 1px solid #3b3f5c; background: #12141f; color: #e2e8f0;',
    '      font-size: 0.95rem; outline: none;',
    '    }',
    '    input[type="text"]:focus { border-color: #7c3aed; box-shadow: 0 0 0 2px rgba(124,58,237,0.3); }',
    '    select {',
    '      padding: 0.6rem 0.9rem; border-radius: 8px; border: 1px solid #3b3f5c;',
    '      background: #12141f; color: #e2e8f0; font-size: 0.95rem; cursor: pointer; outline: none;',
    '    }',
    '    select:focus { border-color: #7c3aed; }',
    '    button.add-btn {',
    '      padding: 0.6rem 1.2rem; border-radius: 8px; border: none;',
    '      background: #7c3aed; color: #fff; font-size: 0.95rem; font-weight: 600;',
    '      cursor: pointer; transition: background 0.15s;',
    '    }',
    '    button.add-btn:hover { background: #6d28d9; }',
    '    .idea-list {',
    '      list-style: none; width: 100%; max-width: 560px;',
    '      display: flex; flex-direction: column; gap: 0.6rem;',
    '    }',
    '    .idea-item {',
    '      display: flex; align-items: center; justify-content: space-between;',
    '      background: #1e2130; border: 1px solid #2d3148; border-radius: 10px;',
    '      padding: 0.75rem 1rem; gap: 0.75rem;',
    '    }',
    '    .idea-title { flex: 1; font-size: 0.95rem; }',
    '    .priority-badge {',
    '      font-size: 0.75rem; font-weight: 700; padding: 0.2rem 0.55rem;',
    '      border-radius: 6px; text-transform: uppercase; letter-spacing: 0.04em;',
    '    }',
    '    .priority-high   { background: #7f1d1d; color: #fca5a5; }',
    '    .priority-medium { background: #78350f; color: #fcd34d; }',
    '    .priority-low    { background: #14532d; color: #86efac; }',
    '    .remove-btn {',
    '      background: transparent; border: 1px solid #4b5563; border-radius: 6px;',
    '      color: #9ca3af; cursor: pointer; font-size: 0.8rem; padding: 0.25rem 0.6rem;',
    '      transition: all 0.15s;',
    '    }',
    '    .remove-btn:hover { background: #7f1d1d; border-color: #ef4444; color: #fca5a5; }',
    '    .empty-state { color: #4b5563; font-size: 0.9rem; text-align: center; padding: 1.5rem 0; }',
  ].join('\n');

  // The client-side script is written as plain strings so the Node.js linter
  // does not interpret it as Node.js code.  escHtml() in the browser script
  // prevents XSS when rendering user-supplied idea titles.
  const clientScript = [
    "    const STORAGE_KEY = 'idea-backlog-v1';",
    '    function loadIdeas() {',
    "      try { return JSON.parse(localStorage.getItem(STORAGE_KEY)) || []; }",
    '      catch { return []; }',
    '    }',
    '    function saveIdeas(ideas) {',
    "      localStorage.setItem(STORAGE_KEY, JSON.stringify(ideas));",
    '    }',
    '    function escHtml(str) {',
    "      return String(str)",
    "        .replace(/&/g, '&amp;').replace(/</g, '&lt;')",
    "        .replace(/>/g, '&gt;').replace(/\"/g, '&quot;');",
    '    }',
    '    function buildIdeaItem(idea, idx) {',
    "      const li = document.createElement('li');",
    "      li.className = 'idea-item';",
    "      li.setAttribute('data-testid', 'idea-item');",
    '',
    "      const titleSpan = document.createElement('span');",
    "      titleSpan.className = 'idea-title';",
    '      titleSpan.textContent = idea.title;',
    '',
    "      const badge = document.createElement('span');",
    "      badge.className = 'priority-badge priority-' + idea.priority;",
    '      badge.textContent = idea.priority;',
    '',
    "      const removeBtn = document.createElement('button');",
    "      removeBtn.className = 'remove-btn';",
    "      removeBtn.setAttribute('data-testid', 'remove-idea-btn');",
    "      removeBtn.setAttribute('data-idx', String(idx));",
    "      removeBtn.textContent = 'Remove';",
    '      removeBtn.addEventListener(\'click\', function() {',
    '        var ideas = loadIdeas();',
    '        ideas.splice(idx, 1);',
    '        saveIdeas(ideas);',
    '        renderIdeas(ideas);',
    '      });',
    '',
    '      li.appendChild(titleSpan);',
    '      li.appendChild(badge);',
    '      li.appendChild(removeBtn);',
    '      return li;',
    '    }',
    '    function renderIdeas(ideas) {',
    "      var list = document.getElementById('idea-list');",
    "      while (list.firstChild) { list.removeChild(list.firstChild); }",
    '      if (ideas.length === 0) {',
    "        var empty = document.createElement('li');",
    "        empty.className = 'empty-state';",
    "        empty.textContent = 'No ideas yet \u2014 add one above!';",
    '        list.appendChild(empty);',
    '        return;',
    '      }',
    '      ideas.forEach(function(idea, idx) {',
    '        list.appendChild(buildIdeaItem(idea, idx));',
    '      });',
    '    }',
    "    document.getElementById('add-idea-btn').addEventListener('click', function() {",
    "      var titleInput = document.getElementById('idea-title-input');",
    "      var prioritySelect = document.getElementById('idea-priority-select');",
    '      var title = titleInput.value.trim();',
    '      if (!title) { titleInput.focus(); return; }',
    '      var ideas = loadIdeas();',
    '      ideas.unshift({ title: title, priority: prioritySelect.value });',
    '      saveIdeas(ideas);',
    '      renderIdeas(ideas);',
    "      titleInput.value = '';",
    '      titleInput.focus();',
    '    });',
    "    document.getElementById('idea-title-input').addEventListener('keydown', function(e) {",
    "      if (e.key === 'Enter') document.getElementById('add-idea-btn').click();",
    '    });',
    '    renderIdeas(loadIdeas());',
  ].join('\n');

  return [
    '<!DOCTYPE html>',
    '<html lang="en">',
    '<head>',
    '  <meta charset="UTF-8" />',
    '  <meta name="viewport" content="width=device-width, initial-scale=1.0" />',
    '  <title>Idea Backlog</title>',
    '  <style>',
    style,
    '  </style>',
    '</head>',
    '<body>',
    '  <h1>Idea Backlog</h1>',
    '  <div class="card">',
    '    <div class="form-row">',
    '      <input type="text" data-testid="idea-title-input" id="idea-title-input" placeholder="Describe your idea\u2026" />',
    '      <select data-testid="idea-priority-select" id="idea-priority-select">',
    '        <option value="high">High</option>',
    '        <option value="medium" selected>Medium</option>',
    '        <option value="low">Low</option>',
    '      </select>',
    '      <button class="add-btn" data-testid="add-idea-btn" id="add-idea-btn">Add</button>',
    '    </div>',
    '  </div>',
    '  <ul class="idea-list" data-testid="idea-list" id="idea-list"></ul>',
    '  <script>',
    clientScript,
    '  </script>',
    '</body>',
    '</html>',
  ].join('\n');
}

function generateQA(prompt) {
  const title = extractTitle(prompt);
  return [
    '## QA Results',
    '',
    '**Subject:** ' + title,
    '',
    '| Test Suite | Tests Run | Passed | Failed | Skipped |',
    '|------------|-----------|--------|--------|---------|',
    '| Unit | 42 | 42 | 0 | 0 |',
    '| Integration | 18 | 17 | 1 | 0 |',
    '| E2E | 10 | 9 | 0 | 1 |',
    '| **Total** | **70** | **68** | **1** | **1** |',
    '',
    '---',
    '',
    '## Evidence',
    '',
    '- All unit tests pass with 100% coverage on critical paths.',
    '- Integration test failure: `POST /api/items` returns 500 when payload exceeds 1 MB — likely a missing request-size guard.',
    '- E2E skip: browser automation flake on mobile viewport — non-blocking for current milestone.',
    '',
    '---',
    '',
    '## Score',
    '',
    '**Overall QA Score: 87 / 100**',
    '',
    '| Dimension | Score |',
    '|-----------|-------|',
    '| Functional correctness | 95 |',
    '| Edge-case handling | 80 |',
    '| Performance (p95 < 300 ms) | 82 |',
    '| Accessibility (WCAG 2.1 AA) | 78 |',
    '',
    '**Verdict:** Ready for staging with one known regression to address before production.',
    '',
    '---',
    '',
    '*Generated by MockProvider — replace with real LLM output before shipping.*',
  ].join('\n');
}

function generateEvaluation(prompt) {
  const title = extractTitle(prompt);
  return [
    '## Evaluation Score',
    '',
    '**Subject:** ' + title,
    '',
    '**Total Score: 74 / 100**',
    '',
    '---',
    '',
    '## Strengths',
    '',
    '1. Clear separation of concerns between layers.',
    '2. Well-defined public contracts / interfaces.',
    '3. Test coverage on the happy path is solid.',
    '4. Documentation covers setup and basic usage.',
    '',
    '---',
    '',
    '## Gaps',
    '',
    '1. Error-handling strategy is inconsistent — some paths swallow exceptions silently.',
    '2. No observability hooks (metrics, structured logs) in production paths.',
    '3. Missing rate-limiting and back-pressure controls.',
    '4. Performance benchmarks have not been established.',
    '',
    '---',
    '',
    '## Next Step',
    '',
    '**Recommended action:** Address error-handling gaps (Gap 1) in the next sprint before adding new features.',
    'This is the highest-leverage improvement and unblocks proper observability work.',
    '',
    '---',
    '',
    '*Generated by MockProvider — replace with real LLM output before shipping.*',
  ].join('\n');
}

// ---------------------------------------------------------------------------
// MockProvider
// ---------------------------------------------------------------------------

class MockProvider extends BaseProvider {
  get name() {
    return 'mock';
  }

  isAvailable() {
    return true;
  }

  async generate(lane, prompt, opts = {}) {
    const start = Date.now();

    logger.lane('mock', 'Generating content for lane "' + lane + '"');

    let content;
    switch (lane) {
      case 'architecture':
        content = generateArchitecture(prompt);
        break;
      case 'planning':
        content = generatePlanning(prompt);
        break;
      case 'research':
        content = generateResearch(prompt);
        break;
      case 'build':
        content = generateBuild();
        break;
      case 'qa':
        content = generateQA(prompt);
        break;
      case 'evaluation':
        content = generateEvaluation(prompt);
        break;
      default:
        content = 'Content generated for lane: ' + lane + '\n\n' + prompt.slice(0, 200);
    }

    const duration = Date.now() - start;
    logger.done('MockProvider finished in ' + duration + 'ms');

    return { content, provider: this.name, duration };
  }
}

module.exports = { MockProvider };
